### ISSUE TITLE
Write up for generating code

### ISSUE THREAD

**Issue by sreeise** [sreeise/graph-rs-sdk#340]
We need a write up of how to generate code for the APIs and to make this easier to do for everyone using the project.

**Comment by kitplummer** [comment]
Definitely interested in this - want to add support for the To Dos API.  Digging now.

**Comment by DevLazio** [comment]
In case you didn't see this thread  @kitplummer : https://github.com/sreeise/graph-rs/discussions/339
It should help you get started. 
A little disclaimer : did that once or twice  and it's not at all straightforward to add new apis, even for simple cases. There is multiple "layers" of macros and it can be a bit overwhelming at first.

**Comment by sreeise** [comment]
Yeah, this is something I have been working toward for a while. But its still needs some work. And I think it might make more sense to get some of these changes that I am currently working on into the codebase before do a write up. Because its going to get outdated quick. And I am also simplifying the process so that its not too overwhelming like DevLazio mentioned.

**Comment by sreeise** [comment]
With the release of 1.0.0, codgen is in a much better place. Maybe a few tweaks to get it more user friendly. I will try to provide a write up soon now that I am freed up to do it.

**Comment by sreeise** [comment]
Started working on the [Wiki](https://github.com/sreeise/graph-rs/wiki). Its not ready yet but its making progress.
