### ISSUE TITLE
Pre-created email message returns 411 code when attempting to send

### ISSUE THREAD

**Issue by buhaytza2005** [sreeise/graph-rs-sdk#466]
**Describe the bug**
When trying to send a pre-created message with attachments, getting a `411` error code
**To Reproduce**
code below: `mail.rs`
```rust
#[derive(Serialize, Deserialize, Debug)]
struct Attachment {
    odata_type: String,
    name: String,
    content_type: String,
    content_bytes: String,
}

fn load_attachments(attachments: Vec<String>) -> io::Result<Vec<Attachment>> {
    let parent_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let mut final_attachments = Vec::new();

    for attachment in attachments {
        let file_path = parent_dir.join(&attachment);
        println!("{:?}", file_path);
        if file_path.is_file() {
            let mut file = File::open(&file_path)?;
            let mut content = Vec::new();
            file.read_to_end(&mut content)?;

            let file_content = encode(&content);
            let file_name = file_path.file_name().unwrap().to_str().unwrap();
            let content_type = from_path(&file_path).first_or_octet_stream().to_string();

            let mut attachment = Attachment {
                odata_type: "#microsoft.graph.fileAttachment".to_string(),
                name: file_name.to_string(),
                content_type: content_type.to_string(),
                content_bytes: file_content,
            };

            if file_name.ends_with(".png") {
                attachment.content_type = "image/png".to_string();
            }

            final_attachments.push(attachment);
        }
    }

    Ok(final_attachments)
}


pub async fn send_email_with_attachments(access_token: &str,
    sender: &str,
    subject: &str,
    body: &str,
    recipients: &str,
    attachments: Vec<&str>) -> GraphResult<()> {

    let recipients = recipients.split(";").collect::<Vec<&str>>();
    let mut client = Graph::new(access_token);

    let recipients_vec = recipients.iter().map(|x| {
        serde_json::json!({
            "emailAddress": {
                "address": x
            }
        })
    }).collect::<Vec<serde_json::Value>>();

    // Convert attachment paths to String
    let attachments: Vec<String> = attachments.iter().map(|&s| s.to_string()).collect();

    let attachment_results = load_attachments(attachments).unwrap();

     // Assuming the Attachment struct can be serialized to JSON
    let attachments_json: Vec<serde_json::Value> = attachment_results.into_iter().map(|att| {
        serde_json::json!({
            "@odata.type": att.odata_type,
            "name": att.name,
            "contentType": att.content_type,
            "contentBytes": att.content_bytes,
        })
    }).collect();
    let message = client
        .user(sender)
        .messages()
        .create_messages(&serde_json::json!({
                "subject": subject,
                "body": {
                    "contentType": "HTML",
                    "content": body
                },
                "toRecipients": recipients_vec,
                "ccRecipients": [
                    {
                        "emailAddress": {
                        "address": "[REDACTED]"
                        }
                    },
                ],
        }))
        .send()
        .await?;
    let message_id: serde_json::Value = message.json().await?;
    println!("{:#?}", message_id);
    let mess_id = message_id.get("id").unwrap().as_str().unwrap();

    for attachment in attachments_json {
        println!("{:?}", attachment);
        let size = attachment["size"].as_u64().expect("SIZE").to_string();
        let att_response = client
            .user(sender)
            .message(mess_id)
            .attachments()
            .create_attachments(&attachment)
            .send()
            .await?;
        let attachment_resp: serde_json::Value = att_response.json().await?;
        println!("{:#?}", attachment_resp);
    }

    let response = client
        .user(sender)
        .message(mess_id)
        .send().send()
        .await?;

    println!("{:#?}", response);


    Ok(())
}
```
Used as below

```rust
use anyhow::Result;
use graph_rs_sdk::Graph;
use lib_o365::mail::{send_email_with_attachments, send_mail};
use lib_o365::utils::misc::get_main_site_id;
use lib_o365::operations::trade_effluent::get_te_files;

#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();
    let access_token = lib_o365::authentication::log_me_in().await.unwrap();
    let client = Graph::new(&access_token);

    let main_site_id = get_main_site_id(&access_token).await;

    let _ = get_te_files(&access_token, "2020").await?;

    let attachments = vec![".temp_files/tst.pdf", ".temp_files/tst2.pdf"];
    let tst = send_email_with_attachments(&access_token,
        "[REDACTED]",
        "test",
        "<p>Test</p>",
        "[REDACTED]",
        attachments).await?;
    Ok(())
}
```

**Expected behavior**

- A draft to be created - OK
- 2 attachments to be added - OK
- Email to be sent - FAIL

The first 2 parts are happening, but when attempting to send the email I get the below:
```
Response {
    url: Url {
        scheme: "https",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "graph.microsoft.com",
            ),
        ),
        port: None,
        path: "/v1.0/users/[REDACTED]/messages/AAMkADdlNzExMGZkLWZkNzktNGZlZi04NDdhLWU2NzhiOWUwMTg1ZABGAAAAAAByLQ6unMc6Som2QHASx_gkBwCNnDcsN4wLRKMyeSAiGEsnAAAAAAEPAACNnDcsN4wLRKMyeSAiGEsnAAV7Ct_HAAA=/send",
        query: None,
        fragment: None,
    },
    status: 411,
    headers: {
        "content-type": "text/html; charset=us-ascii",
        "date": "Wed, 06 Mar 2024 08:36:00 GMT",
        "connection": "close",
        "content-length": "344",
    },
}
```
Looking at MS docs :

<img width="439" alt="image" src="https://github.com/sreeise/graph-rs-sdk/assets/44904160/3c16449b-a155-4994-b11c-9a0818e81a59">

As far as I can tell, the last trigger to send the email expects a `Content-Length` header that I would be expecting to be inferred as it is when doing a `.send_mail()`

I have tried even a more basic example of not adding attachments but the result is the same. Am I missing a trick here or should the header be added manually? 

**Desktop (please complete the following information):**
 - OS: wsl2 

**Additional context**

**Comment by sreeise** [comment]
> **Describe the bug** A clear and concise description of what the bug is. When trying to send a pre-created message with attachments, getting a `411` error code **To Reproduce** code below: `mail.rs`
> 
> ```rust
> #[derive(Serialize, Deserialize, Debug)]
> struct Attachment {
>     odata_type: String,
>     name: String,
>     content_type: String,
>     content_bytes: String,
> }
> 
> fn load_attachments(attachments: Vec<String>) -> io::Result<Vec<Attachment>> {
>     let parent_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
>     let mut final_attachments = Vec::new();
> 
>     for attachment in attachments {
>         let file_path = parent_dir.join(&attachment);
>         println!("{:?}", file_path);
>         if file_path.is_file() {
>             let mut file = File::open(&file_path)?;
>             let mut content = Vec::new();
>             file.read_to_end(&mut content)?;
> 
>             let file_content = encode(&content);
>             let file_name = file_path.file_name().unwrap().to_str().unwrap();
>             let content_type = from_path(&file_path).first_or_octet_stream().to_string();
> 
>             let mut attachment = Attachment {
>                 odata_type: "#microsoft.graph.fileAttachment".to_string(),
>                 name: file_name.to_string(),
>                 content_type: content_type.to_string(),
>                 content_bytes: file_content,
>             };
> 
>             if file_name.ends_with(".png") {
>                 attachment.content_type = "image/png".to_string();
>             }
> 
>             final_attachments.push(attachment);
>         }
>     }
> 
>     Ok(final_attachments)
> }
> 
> 
> pub async fn send_email_with_attachments(access_token: &str,
>     sender: &str,
>     subject: &str,
>     body: &str,
>     recipients: &str,
>     attachments: Vec<&str>) -> GraphResult<()> {
> 
>     let recipients = recipients.split(";").collect::<Vec<&str>>();
>     let mut client = Graph::new(access_token);
> 
>     let recipients_vec = recipients.iter().map(|x| {
>         serde_json::json!({
>             "emailAddress": {
>                 "address": x
>             }
>         })
>     }).collect::<Vec<serde_json::Value>>();
> 
>     // Convert attachment paths to String
>     let attachments: Vec<String> = attachments.iter().map(|&s| s.to_string()).collect();
> 
>     let attachment_results = load_attachments(attachments).unwrap();
> 
>      // Assuming the Attachment struct can be serialized to JSON
>     let attachments_json: Vec<serde_json::Value> = attachment_results.into_iter().map(|att| {
>         serde_json::json!({
>             "@odata.type": att.odata_type,
>             "name": att.name,
>             "contentType": att.content_type,
>             "contentBytes": att.content_bytes,
>         })
>     }).collect();
>     let message = client
>         .user(sender)
>         .messages()
>         .create_messages(&serde_json::json!({
>                 "subject": subject,
>                 "body": {
>                     "contentType": "HTML",
>                     "content": body
>                 },
>                 "toRecipients": recipients_vec,
>                 "ccRecipients": [
>                     {
>                         "emailAddress": {
>                         "address": "[REDACTED]"
>                         }
>                     },
>                 ],
>         }))
>         .send()
>         .await?;
>     let message_id: serde_json::Value = message.json().await?;
>     println!("{:#?}", message_id);
>     let mess_id = message_id.get("id").unwrap().as_str().unwrap();
> 
>     for attachment in attachments_json {
>         println!("{:?}", attachment);
>         let size = attachment["size"].as_u64().expect("SIZE").to_string();
>         let att_response = client
>             .user(sender)
>             .message(mess_id)
>             .attachments()
>             .create_attachments(&attachment)
>             .send()
>             .await?;
>         let attachment_resp: serde_json::Value = att_response.json().await?;
>         println!("{:#?}", attachment_resp);
>     }
> 
>     let response = client
>         .user(sender)
>         .message(mess_id)
>         .send().send()
>         .await?;
> 
>     println!("{:#?}", response);
> 
> 
>     Ok(())
> }
> ```
> 
> Used as below
> 
> ```rust
> use anyhow::Result;
> use graph_rs_sdk::Graph;
> use lib_o365::mail::{send_email_with_attachments, send_mail};
> use lib_o365::utils::misc::get_main_site_id;
> use lib_o365::operations::trade_effluent::get_te_files;
> 
> #[tokio::main]
> async fn main() -> Result<()> {
>     env_logger::init();
>     let access_token = lib_o365::authentication::log_me_in().await.unwrap();
>     let client = Graph::new(&access_token);
> 
>     let main_site_id = get_main_site_id(&access_token).await;
> 
>     let _ = get_te_files(&access_token, "2020").await?;
> 
>     let attachments = vec![".temp_files/tst.pdf", ".temp_files/tst2.pdf"];
>     let tst = send_email_with_attachments(&access_token,
>         "[REDACTED]",
>         "test",
>         "<p>Test</p>",
>         "[REDACTED]",
>         attachments).await?;
>     Ok(())
> }
> ```
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
>     * A draft to be created - OK
> 
>     * 2 attachments to be added - OK
> 
>     * Email to be sent - FAIL
> 
> 
> The first 2 parts are happening, but when attempting to send the email I get the below:
> 
> ```
> Response {
>     url: Url {
>         scheme: "https",
>         cannot_be_a_base: false,
>         username: "",
>         password: None,
>         host: Some(
>             Domain(
>                 "graph.microsoft.com",
>             ),
>         ),
>         port: None,
>         path: "/v1.0/users/[REDACTED]/messages/AAMkADdlNzExMGZkLWZkNzktNGZlZi04NDdhLWU2NzhiOWUwMTg1ZABGAAAAAAByLQ6unMc6Som2QHASx_gkBwCNnDcsN4wLRKMyeSAiGEsnAAAAAAEPAACNnDcsN4wLRKMyeSAiGEsnAAV7Ct_HAAA=/send",
>         query: None,
>         fragment: None,
>     },
>     status: 411,
>     headers: {
>         "content-type": "text/html; charset=us-ascii",
>         "date": "Wed, 06 Mar 2024 08:36:00 GMT",
>         "connection": "close",
>         "content-length": "344",
>     },
> }
> ```
> 
> Looking at MS docs :
> <img alt="image" width="439" src="https://private-user-images.githubusercontent.com/44904160/310425361-3c16449b-a155-4994-b11c-9a0818e81a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTEwNTYsIm5iZiI6MTcwOTc5MDc1NiwicGF0aCI6Ii80NDkwNDE2MC8zMTA0MjUzNjEtM2MxNjQ0OWItYTE1NS00OTk0LWIxMWMtOWEwODE4ZTgxYTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA1NTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZDYwZWViMTY1NDUzZjMzYzM1MDFlYWE2NTk3MjAyNDkxNzIyODBlNmEzNjM5Njk0ZWVhODM5YzRlMjQ1MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pQMvBvZw5C8CUycYMnIJYMdd3lPKL2EhGp6AYEd6K2o">
> 
> As far as I can tell, the last trigger to send the email expects a `Content-Length` header that I would be expecting to be inferred as it is when doing a `.send_mail()`
> 
> I have tried even a more basic example of not adding attachments but the result is the same. Am I missing a trick here or should the header be added manually?
> 
> **Desktop (please complete the following information):**
> 
>     * OS: wsl2
> 
> 
> **Additional context** Add any other context about the problem here.

The header has to be added manually. I don't believe there is any ineferring of the content length when doing send mail either. This is something that can be added as a feature. Right now, headers for the most part are left up to the user except in doing certain things like upload sessions.

**Comment by sreeise** [comment]
> Got it working. All it took was to add the header with a value of 0. When tinkering with the request with curl to understand why the direct link would send the email through MS Graph explorer but not from the command line, passing `-d {}` to curl made the request a success. I'll submit a PR with this an example to make it clearer.
> 
> ```rust
> let response = client
>         .user(sender)
>         .message(mess_id)
>         .send().header(CONTENT_LENGTH, HeaderValue::from_str("0").unwrap())
>         .send()
>         .await?;
> ```
> 
> Thanks for your response.

Ah, ok I thought you were sending an actual file or something which is what confused me. Yeah the content length has to be set to 0 when there is not a body.

**Comment by sreeise** [comment]
@buhaytza2005 I am going to close this one out now that you have added an example. If you think this should be a feature you can open a new ticket, I don't mind at all. I don't know off the top of my head if the OpenAPI can tell us whether to add this for these types of requests but its something we could possibly look into.
