### ISSUE TITLE
Support persisting credentials to avoid re-auth on restart

### ISSUE THREAD

**Issue by andre-volvo** [sreeise/graph-rs-sdk#470]
Right now, my container needs to reauthenticate every time it is restarted, despite having access to a long-lived refresh token. Ideally, this would be avoided by persisting the refresh token, and then re-creating the credential from it on startup.

However, I've found no way to create a credential from a refresh token, just a regular short-lived access token, and likewise no way to access the refresh token inside a credential.

My suggestion is thus to either provide a new `RefreshTokenCredential`, or provide methods to construct other credentials from a refresh token.

**Comment by sreeise** [comment]
@andre-volvo Sorry I am just now getting back to this. Can you tell me what version your using? The 2.0 version being released here shortly within a couple days is a rewrite of how oauth works. 

2.0 will have in memory persistance but after that is released the plan is to add persistance via Azure as well as for desktop.

**Comment by andre-volvo** [comment]
No worries! I am using 2.0.0-beta.0, and yeah I meant Azure Key Vault.

I managed to solve it by keeping the credential around alongside the `GraphClient` and, on `Drop`, call `credential.execute_async()` and parse it as a `Token` to get a fresh refresh token, and then store it in a key vault.
And then I just check on startup if a token exists and works 😄

**Comment by sreeise** [comment]
> No worries! I am using 2.0.0-beta.0, and yeah I meant Azure Key Vault.
> 
> I managed to solve it by keeping the credential around alongside the `GraphClient` and, on `Drop`, call `credential.execute_async()` and parse it as a `Token` to get a fresh refresh token, and then store it in a key vault. And then I just check on startup if a token exists and works 😄

Sounds good. Im gonna close this one out as this feature request is covered in #432
