### ISSUE TITLE
Update README documentation examples to use `GraphClient` naming

### ISSUE THREAD

**Issue by sreeise** [sreeise/graph-rs-sdk#473]
Update README documentation examples to use `GraphClient` instead of `Graph`. Both are valid but the name has been updated to `GraphClient` while `Graph` is an alias.

**Comment by buhaytza2005** [comment]
I assume this would involve updating the examples too? Might look a bit confusing if the README has `GraphClient` and the examples have `Graph`?

Happy to work on this if that's OK with you

**Comment by sreeise** [comment]
> I assume this would involve updating the examples too? Might look a bit confusing if the README has `GraphClient` and the examples have `Graph`?
> 
> Happy to work on this if that's OK with you

Yep that works. Really I included `Graph` in 2.0 as an alias to make it easier for people who wanted to use 2.0 without having to make a bunch of code changes.

I think I may have updated a lot of the example code to use `GraphClient` but yes if you see any that are not changed please update them.

Thanks for taking this on.

**Comment by sreeise** [comment]
Updated in #479
