### ISSUE TITLE
Generate devices API - /devices

### ISSUE THREAD

**Issue by knoxfighter** [sreeise/graph-rs-sdk#482]
Consider whether this request is within the scope of the repository or whether it might better be served by first having a conversation by opening a discussion in the [Discussions tab](https://github.com/sreeise/graph-rs-sdk/discussions).

**Give a detailed description of the feature request**
We have intune devices and want to read/add extension properties with it. The extension property fields can be set with:
```powershell
# Write
$Param = @{
    ExtensionAttribute1 = "Test"
}
Update-MgBetaDevice -DeviceId "<ID>" -ExtensionAttributes $Param


# Read
$test = Get-MgBetaDeviceByDeviceId -DeviceId "<ID>" | Select-Object -Property Id, ExtensionAttributes, DisplayName
$test.ExtensionAttributes.ExtensionAttribute1
```
```http
## Write
PATCH https://graph.microsoft.com/v1.0/devices/<Id>
Content-type: application/json

{
    "extensionAttributes": {
        "extensionAttribute1": "BYOD-Device"
    }
}
```

Unfortunately the whole /devices/ endpoint is not mapped. Please add a mapping for it.

Best regards,
knox

**Comment by sreeise** [comment]
@knoxfighter Thanks for reporting.

**Comment by sreeise** [comment]
Merged changes for the devices APIs. Let me know if everything is working for you if you get a chance.

**Comment by sreeise** [comment]
> Since i only use one endpoint, i only tested that one:
> 
> ```rust
> let body = json!({
>     "extensionAttributes": {
>         "extensionAttribute1": data
>     }
> });
> let res = graph_client.devices().update_device_by_device_id(azure_id, &body).into_blocking().send();
> ```
> 
> This works perfectly without any issues, thank you very much.

Glad to hear.
