### ISSUE TITLE
BUG: `Arc<GraphClient>` which is not `Send`

### ISSUE THREAD

**Issue by Jeadie** [sreeise/graph-rs-sdk#491]
**Describe the bug**
`Arc<GraphClient>` is no longer `Send`.

Because of 
```
the trait `std::marker::Sync` is not implemented for 
  `dyn CloneService<Request, Error = Box<dyn Error + Send + Sync>, Future = Pin<Box<dyn Future<Output = Result<Response, Box<dyn Error + Send + Sync>>> + Send>>, Response = Response> + Send`, 
which is required by ...
```

This comes from #469  adding
```rust
pub(crate) service: BoxCloneService<Request, Response, Box<dyn std::error::Error + Send + Sync>>,
```

see [line changes](https://github.com/sreeise/graph-rs-sdk/pull/469/files#diff-41502d0075577d5459a17bf7b5eafd5ba96239f80f9f91270e1c2b076297472fR348-R349).

**Comment by sreeise** [comment]
Thanks for reporting this. There might have to be some changes to how the tower service is being stored here. I looked at this a little bit and tried just wrapping the `BoxCloneService` in an `Arc<Mutex<..>>` but that causes some ownership problems with the RequestHandler.

Possibly the best thing is to only store the configuration for the tower service and move the actual service setup to `RequestHanlder` which would make `GraphClient` sync again. I'll have to look into this more.
